# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: CD to web-api Directory
      run: cd ~/plus-nine-backend
    - name: Change branch
      run: git checkout main
    - name: Pull changes
      run: git pull
    - name: Stop current docker container
      run: docker stop web-api-plusnine
    - name: Delete current docker container
      run: docker rm web-api-plusnine
    - name: Remove current DiscordBot Image
      run: docker rmi --force web-api-plusnine
    - name: Build the Docker image
      run: docker build --rm -t web-api-plusnine .
    - name: Run Docker container
      run: docker run -p 5000:5000 -p 5001:5001 -e ASPNETCORE_HTTP_PORT=https://+:5001 -e ASPNETCORE_URLS=http://+:5000 --name web-api-plusnine --restart=always web-api-plusnine
